---
name: Mise Buildkite Plugin
description: Activate Mise environment
author: https://github.com/nkvoll
requirements: []
configuration:
  type: object
  additionalProperties: false
  properties:
    version:
      type: string
      default: ""
      description: Version of Mise to install (e.g "YYYY.MM.DD").
    install:
      type: boolean
      default: true
      description: Install the tools specified in the mise.toml file.
    redact:
      type: boolean
      default: true
      description: Redact sensitive environment variables from build logs.
    env:
      type: string
      default: ""
      description: Environment to use for mise commands
    export_env:
      type: boolean
      default: true
      description: Export environment variables defined in mise.toml to the
        build environment.
    doctor:
      type: boolean
      default: true
      description: Run 'mise doctor' to validate the setup.
