---
# $yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json
steps:
  - label: "Verify Renovate configuration"
    id: "verify-renovate-configuration"
    if_changed:
      include:
        # if our Renovate configuration is amended, then make sure we have well-formed config
        # for more info, see https://docs.elastic.dev/plat-prod-team/service-catalogue/renovate/testing-renovate-changes
        - "renovate.json"
    command: "renovate-config-validator"
    agents:
      image: "docker.elastic.co/ci-agent-images/pipelib:0.25.0@sha256:1e7cbd9859c9d4d16471b99c4d734709340d7c584401a62b762ca1592c2e5df0"

  - label: "Verify Renovate configuration"
    id: "validate-catalog-info"
    if_changed:
      include:
        # if our catalog-info.yaml is changed, make sure it's well-formed according to our internal standards as well as Backstage's validation
        - "catalog-info.yaml"
    command: "/agent/check-catalog-info.sh"
    agents:
      image: "docker.elastic.co/ci-agent-images/pipelib:0.25.0@sha256:1e7cbd9859c9d4d16471b99c4d734709340d7c584401a62b762ca1592c2e5df0"

  - label: "🐚 Lint"
    id: "lint"
    plugins:
      - elastic/mise#${BUILDKITE_COMMIT}: ~
    command: |
      make ci-lint

  - label: "✅ Validate usage"
    id: "validate-usage"
    plugins:
      - elastic/mise#${BUILDKITE_COMMIT}:
          env: test
    command: |
      yq --version

  - label: "🔬 pre-commit"
    id: "pre-commit"
    plugins:
      - elastic/mise#${BUILDKITE_COMMIT}: ~
    command: |
      make pre-commit

  - label: "🔨 Plugin Tester"
    id: "plugin-tester"
    plugins:
      - plugin-tester#v1.3.0: ~
    agents:
      provider: "gcp"
      image: "family/core-ubuntu-2404"
      machineType: "n2-standard-8"
