---
# $yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json
steps:
  - label: "🔄 Triggering platform pipelines"
    id: "trigger-platform-pipelines"
    plugins:
      - monorepo-diff#v1.5.1:
          diff: ".buildkite/diff ${BUILDKITE_COMMIT}"
          wait: true
          watch:
            # if our Renovate configuration is amended, then make sure we have well-formed config
            # for more info, see https://docs.elastic.dev/plat-prod-team/service-catalogue/renovate/testing-renovate-changes
            - path: "renovate.json"
              config:
                label: "Verify Renovate configuration"
                command: "renovate-config-validator"
                id: "verify-renovate-configuration"
                agents:
                  image: "docker.elastic.co/ci-agent-images/pipelib:0.23.0@sha256:69094e7e5fa1e252da2171fdf707bf3408c5e576e86ac64d8d667498bc1b627d"
            # if our catalog-info.yaml is changed, make sure it's well-formed according to our internal standards as well as Backstage's validation
            - path: "catalog-info.yaml"
              config:
                command: "/agent/check-catalog-info.sh"
                id: "validate-catalog-info"
                agents:
                  image: "docker.elastic.co/ci-agent-images/pipelib:0.23.0@sha256:69094e7e5fa1e252da2171fdf707bf3408c5e576e86ac64d8d667498bc1b627d"

  - label: "🐚 Lint"
    id: "lint"
    plugins:
      - ${BUILDKITE_ORGANIZATION_SLUG:-elastic}/mise#${BUILDKITE_BRANCH:-main}: ~
    command: |
      make ci-lint

  - label: "✅ Validate usage"
    id: "validate-usage"
    plugins:
      - ${BUILDKITE_ORGANIZATION_SLUG:-elastic}/mise#${BUILDKITE_BRANCH:-main}:
          env: test
    command: |
      yq --version

  - label: "🔬 pre-commit"
    id: "pre-commit"
    plugins:
      - ${BUILDKITE_ORGANIZATION_SLUG:-elastic}/mise#${BUILDKITE_BRANCH:-main}: ~
    command: |
      make pre-commit

  - label: "🔨 Plugin Tester"
    id: "plugin-tester"
    plugins:
      - plugin-tester#v1.2.0: ~
    agents:
      provider: "gcp"
      image: "family/core-ubuntu-2404"
      machineType: "n2-standard-8"
